### PR TITLE
GU 17.9 - Buffs - Crafting Stations & GU 18.5 - Bazaar Strings

### PR DESCRIPTION
**Pull request by BubbaJoeX**

### CODE REVIEW

**Comment by Cekis** [comment]
@SWG-Source/qa can you guys please test this out?

**Comment by Cekis** [comment]
@BubbaJoeX Sorry, just saw this... what does this fix?  Do you have a description at the minimum?

**Comment by langelusse** [comment]
So for me I have no error for crafting station and STAP speeder it's not allowed to sell inside bazaar

**Comment by BubbaJoeX** [comment]
Crafting Station buffs can no longer be dispelled.

And the STAP-1 Deed has the correct string.

**Pull request merged**
