### PR TITLE
Trader and Entertainer Heroic Jewelry

### PR DESCRIPTION
**Pull request by TyroneSWG**

### CODE REVIEW

**Comment by TyroneSWG** [comment]
The set names that pull from the columns in the datatables already have the set_trader and set_ent in it. I'll double check though.

**Comment by TyroneSWG** [comment]
https://github.com/SWG-Source/dsrc/blob/78f049a3f4cf50596c8eee2208db452b43d8330e/sku.0/sys.server/compiled/game/script/terminal/terminal_character_builder.java#L7164

**Comment by seefo** [comment]
https://github.com/SWG-Source/dsrc/issues/25

**Comment by seefo** [comment]
Seems to be for issue https://github.com/SWG-Source/dsrc/issues/25

**Comment by TyroneSWG** [comment]
Forgot to put a new line on the tab file. Added that.

**Pull request merged**
